package org.myalice.domain.websocket;

import java.util.Date;

public class TalkRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_record.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_record.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_record.from_user_id
     *
     * @mbg.generated
     */
    private String fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_record.from_user_name
     *
     * @mbg.generated
     */
    private String fromUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_record.to_user_id
     *
     * @mbg.generated
     */
    private String toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_record.to_user_name
     *
     * @mbg.generated
     */
    private String toUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_record.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_record.connection_id
     *
     * @mbg.generated
     */
    private String connectionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_record.from_ip
     *
     * @mbg.generated
     */
    private String fromIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column talk_record.to_ip
     *
     * @mbg.generated
     */
    private String toIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_record.id
     *
     * @return the value of talk_record.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_record.id
     *
     * @param id the value for talk_record.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_record.content
     *
     * @return the value of talk_record.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_record.content
     *
     * @param content the value for talk_record.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_record.from_user_id
     *
     * @return the value of talk_record.from_user_id
     *
     * @mbg.generated
     */
    public String getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_record.from_user_id
     *
     * @param fromUserId the value for talk_record.from_user_id
     *
     * @mbg.generated
     */
    public void setFromUserId(String fromUserId) {
        this.fromUserId = fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_record.from_user_name
     *
     * @return the value of talk_record.from_user_name
     *
     * @mbg.generated
     */
    public String getFromUserName() {
        return fromUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_record.from_user_name
     *
     * @param fromUserName the value for talk_record.from_user_name
     *
     * @mbg.generated
     */
    public void setFromUserName(String fromUserName) {
        this.fromUserName = fromUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_record.to_user_id
     *
     * @return the value of talk_record.to_user_id
     *
     * @mbg.generated
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_record.to_user_id
     *
     * @param toUserId the value for talk_record.to_user_id
     *
     * @mbg.generated
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_record.to_user_name
     *
     * @return the value of talk_record.to_user_name
     *
     * @mbg.generated
     */
    public String getToUserName() {
        return toUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_record.to_user_name
     *
     * @param toUserName the value for talk_record.to_user_name
     *
     * @mbg.generated
     */
    public void setToUserName(String toUserName) {
        this.toUserName = toUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_record.type
     *
     * @return the value of talk_record.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_record.type
     *
     * @param type the value for talk_record.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_record.create_time
     *
     * @return the value of talk_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_record.create_time
     *
     * @param createTime the value for talk_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_record.connection_id
     *
     * @return the value of talk_record.connection_id
     *
     * @mbg.generated
     */
    public String getConnectionId() {
        return connectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_record.connection_id
     *
     * @param connectionId the value for talk_record.connection_id
     *
     * @mbg.generated
     */
    public void setConnectionId(String connectionId) {
        this.connectionId = connectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_record.from_ip
     *
     * @return the value of talk_record.from_ip
     *
     * @mbg.generated
     */
    public String getFromIp() {
        return fromIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_record.from_ip
     *
     * @param fromIp the value for talk_record.from_ip
     *
     * @mbg.generated
     */
    public void setFromIp(String fromIp) {
        this.fromIp = fromIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column talk_record.to_ip
     *
     * @return the value of talk_record.to_ip
     *
     * @mbg.generated
     */
    public String getToIp() {
        return toIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column talk_record.to_ip
     *
     * @param toIp the value for talk_record.to_ip
     *
     * @mbg.generated
     */
    public void setToIp(String toIp) {
        this.toIp = toIp;
    }
}