package com.myalice.domain;

import java.util.Date;

public class QuestionOrderAttachment extends BaseDomain {
    
	private static final long serialVersionUID = 1L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order_attachment.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order_attachment.question_order_id
     *
     * @mbg.generated
     */
    private String questionOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order_attachment.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order_attachment.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_order_attachment.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order_attachment.id
     *
     * @return the value of question_order_attachment.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order_attachment.id
     *
     * @param id the value for question_order_attachment.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order_attachment.question_order_id
     *
     * @return the value of question_order_attachment.question_order_id
     *
     * @mbg.generated
     */
    public String getQuestionOrderId() {
        return questionOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order_attachment.question_order_id
     *
     * @param questionOrderId the value for question_order_attachment.question_order_id
     *
     * @mbg.generated
     */
    public void setQuestionOrderId(String questionOrderId) {
        this.questionOrderId = questionOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order_attachment.create_time
     *
     * @return the value of question_order_attachment.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order_attachment.create_time
     *
     * @param createTime the value for question_order_attachment.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order_attachment.status
     *
     * @return the value of question_order_attachment.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order_attachment.status
     *
     * @param status the value for question_order_attachment.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_order_attachment.url
     *
     * @return the value of question_order_attachment.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_order_attachment.url
     *
     * @param url the value for question_order_attachment.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }
}